[package]
name = "transfer-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
clap = { version = "4.3", features = ["derive"] }
indicatif = "0.17"
bytes = "1.4"
sha2 = "0.10"
hex = "0.4"
thiserror = "1.0"